### PR TITLE
feat(apple_google_pay): add example with hooks

### PR DESCRIPTION
**Pull request by KevinOl**

### CODE REVIEW

**Comment by KevinOl** [comment]
@pstadler @dmengelt

**Comment by pstadler** [comment]
Thanks for your PR. It may takes some time until I'm able to review this.

**Comment by KevinOl** [comment]
- Put everything related to your component in a single file. This is an example and shouldn't be split into multiple files, so people can basically copy paste a single file and move on from there.
**Done all in PaymentButtonWithHook.js**

- When toggling your component, there's no check whether payment-button.js already exists and it gets loaded several times.
**Added check (cachedScripts)**
 
- When loading the example page, payment-button.js gets immediately loaded twice, please investigate.
**With the check this should not happen**
 
- Please rename MOCK to something like OPTIONS.
**Done**
 
- Even though we don't provide any linting yet, please use single quotes and no semicolons. When I open a PR in another repository, I try to match my code style with what's already there.
**Yeah I was not sure because I thought maybe you guys will be changing as your 'likes'. Also providing an .editorconfig by default could be nicer rather than figuring out what the format is. Just as suggestion.**

**Comment by pstadler** [comment]
> Even though we don't provide any linting yet, please use single quotes and no semicolons. When I open a PR in another repository, I try to match my code style with what's already there.
> **Yeah I was not sure because as an example I thought maybe you guys will be changing as your 'likes'. Also providing an .editorconfig by default could be nicer rather than figuring out what the format is. Just as suggestion.**

Didn't want to sound rude and I'm fully aware that this repo doesn't contain much tooling goodness at this point. Thanks for your effort 👍

**Comment by pstadler** [comment]
This looks great now, thanks again!

**Comment by fgrDtrx** [comment]
Hi @KevinOl, the bug @pstadler mentioned was fixed and deployed to our sandbox. Thanks a lot for your valuable inputs!

**Pull request merged**
